import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 80, fontFamily: 'Helvetica', color: '#1a1a1a' },
  border: { position: 'absolute', top: 30, left: 30, right: 30, bottom: 30, borderWidth: 2, borderColor: '#e5e7eb', borderStyle: 'solid' },
  title: { fontSize: 22, fontWeight: 'bold', marginBottom: 8, color: '#0f0f0f' },
  subtitle: { fontSize: 12, color: '#666666', marginBottom: 48 },
  label: { fontSize: 11, color: '#999999', marginBottom: 4 },
  name: { fontSize: 20, fontWeight: 'bold', color: '#0f0f0f', marginBottom: 8 },
  module: { fontSize: 13, color: '#333333', marginBottom: 48 },
  meta: { fontSize: 9, color: '#999999', marginTop: 48, lineHeight: 1.8 },
})

export function AttestationPDF({
  userName, orgName, moduleTitle, completedAt, quizScore, totalQuestions,
}: {
  userName: string
  orgName: string
  moduleTitle: string
  completedAt: Date
  quizScore: number
  totalQuestions: number
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page} orientation="landscape">
        <View style={styles.border} />
        <Text style={styles.title}>Certificate of Completion</Text>
        <Text style={styles.subtitle}>AI Literacy Training — EU AI Act Article 4</Text>
        <Text style={styles.label}>This certifies that</Text>
        <Text style={styles.name}>{userName}</Text>
        <Text style={styles.label}>of {orgName} has successfully completed</Text>
        <Text style={styles.module}>{moduleTitle}</Text>
        <Text style={styles.label}>Quiz score: {quizScore}/{totalQuestions}</Text>
        <Text style={styles.meta}>
          {`Completed: ${completedAt.toLocaleDateString('en-GB')}\nGenerated by AIActReady | Not legal advice`}
        </Text>
      </Page>
    </Document>
  )
}
