import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const s = StyleSheet.create({
  coverPage: { padding: 80, fontFamily: 'Helvetica', backgroundColor: '#0f0f0f', flex: 1 },
  coverTitle: { fontSize: 28, color: '#ffffff', fontWeight: 'bold', marginBottom: 12 },
  coverSub: { fontSize: 13, color: '#aaaaaa', marginBottom: 48 },
  coverMeta: { fontSize: 10, color: '#666666', lineHeight: 1.8 },
  coverDisclaimer: { marginTop: 120, padding: 12, backgroundColor: '#1a1a1a', fontSize: 8, color: '#666666', lineHeight: 1.5 },
  contentPage: { padding: 60, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a', lineHeight: 1.6 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 16, color: '#0f0f0f', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', borderBottomStyle: 'solid', paddingBottom: 8 },
  heading: { fontSize: 11, fontWeight: 'bold', marginTop: 14, marginBottom: 6 },
  body: { fontSize: 10, color: '#333333', lineHeight: 1.7 },
  tableHeader: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#333333', borderBottomStyle: 'solid', paddingVertical: 6 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f0f0f0', borderBottomStyle: 'solid', paddingVertical: 6 },
  cell: { flex: 1, fontSize: 9 },
  footer: { position: 'absolute', bottom: 30, left: 60, right: 60, fontSize: 8, color: '#999999', textAlign: 'center' },
})

type Tool = { name: string; vendor: string | null; department: string | null; riskClass: string | null; wizardCompleted: boolean }
type DocSection = { id: string; heading: string; content: string }
type Doc = { title: string; type: string; content: { sections: DocSection[] } }
type Assignment = { userName: string; moduleTitle: string; completedAt: Date | null; quizScore: number | null }

function FooterText({ orgName }: { orgName: string }) {
  return (
    <Text
      style={s.footer}
      render={({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
        `${orgName} | AI Compliance Audit Pack | Page ${pageNumber} of ${totalPages}`
      }
      fixed
    />
  )
}

export function AuditPackPDF({
  orgName, frameworks, generatedAt, tools, documents, assignments,
}: {
  orgName: string
  frameworks: string[]
  generatedAt: Date
  tools: Tool[]
  documents: Doc[]
  assignments: Assignment[]
}) {
  return (
    <Document>
      {/* Cover */}
      <Page size="A4" style={s.coverPage}>
        <Text style={s.coverTitle}>AI Compliance Audit Pack</Text>
        <Text style={s.coverSub}>{orgName}</Text>
        <Text style={s.coverMeta}>Generated: {generatedAt.toLocaleDateString('en-GB')}</Text>
        <Text style={s.coverMeta}>Frameworks: {frameworks.join(', ')}</Text>
        <Text style={s.coverMeta}>Prepared by AIActReady</Text>
        <View style={s.coverDisclaimer}>
          <Text>This document was generated by AIActReady and requires review and sign-off by a qualified legal or compliance professional before use in regulatory submissions. AIActReady does not provide legal advice.</Text>
        </View>
      </Page>

      {/* Inventory Register */}
      <Page size="A4" style={s.contentPage}>
        <Text style={s.sectionTitle}>AI Inventory Register</Text>
        <View style={s.tableHeader}>
          {['Tool', 'Vendor', 'Department', 'Risk Class', 'Assessed'].map(h => (
            <Text key={h} style={[s.cell, { fontWeight: 'bold' }]}>{h}</Text>
          ))}
        </View>
        {tools.map((tool, i) => (
          <View key={i} style={s.tableRow}>
            <Text style={s.cell}>{tool.name}</Text>
            <Text style={s.cell}>{tool.vendor ?? '—'}</Text>
            <Text style={s.cell}>{tool.department ?? '—'}</Text>
            <Text style={s.cell}>{tool.riskClass ?? 'Not assessed'}</Text>
            <Text style={s.cell}>{tool.wizardCompleted ? 'Yes' : 'No'}</Text>
          </View>
        ))}
        <FooterText orgName={orgName} />
      </Page>

      {/* Documents */}
      {documents.map((doc, di) => (
        <Page key={di} size="A4" style={s.contentPage}>
          <Text style={s.sectionTitle}>{doc.title}</Text>
          {doc.content.sections.map(section => (
            <View key={section.id}>
              <Text style={s.heading}>{section.heading}</Text>
              <Text style={s.body}>{section.content}</Text>
            </View>
          ))}
          <FooterText orgName={orgName} />
        </Page>
      ))}

      {/* Training Records */}
      <Page size="A4" style={s.contentPage}>
        <Text style={s.sectionTitle}>AI Literacy Training Records (Article 4)</Text>
        <View style={s.tableHeader}>
          {['Name', 'Module', 'Completed', 'Score'].map(h => (
            <Text key={h} style={[s.cell, { fontWeight: 'bold' }]}>{h}</Text>
          ))}
        </View>
        {assignments.map((a, i) => (
          <View key={i} style={s.tableRow}>
            <Text style={s.cell}>{a.userName}</Text>
            <Text style={s.cell}>{a.moduleTitle}</Text>
            <Text style={s.cell}>{a.completedAt ? a.completedAt.toLocaleDateString('en-GB') : 'Not completed'}</Text>
            <Text style={s.cell}>{a.quizScore != null ? `${a.quizScore}/3` : '—'}</Text>
          </View>
        ))}
        <FooterText orgName={orgName} />
      </Page>
    </Document>
  )
}
