import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 60, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a', lineHeight: 1.6 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 24, color: '#0f0f0f' },
  sectionHeading: { fontSize: 12, fontWeight: 'bold', marginTop: 20, marginBottom: 8, color: '#0f0f0f' },
  sectionContent: { fontSize: 10, color: '#333333', lineHeight: 1.7 },
  footer: { position: 'absolute', bottom: 40, left: 60, right: 60, fontSize: 8, color: '#999999', textAlign: 'center' },
  disclaimer: { marginTop: 40, padding: 12, backgroundColor: '#f5f5f5', fontSize: 8, color: '#666666', lineHeight: 1.5 },
})

type Section = { id: string; heading: string; content: string }

export function DocumentPDF({
  title, sections, orgName,
}: {
  title: string
  sections: Section[]
  orgName: string
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        {sections.map(section => (
          <View key={section.id}>
            <Text style={styles.sectionHeading}>{section.heading}</Text>
            <Text style={styles.sectionContent}>{section.content}</Text>
          </View>
        ))}
        <View style={styles.disclaimer}>
          <Text>
            This document was generated by AIActReady and requires review and sign-off by a qualified legal or compliance
            professional before use in regulatory submissions. AIActReady does not provide legal advice.
          </Text>
        </View>
        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) =>
            `${orgName} | Generated ${new Date().toLocaleDateString('en-GB')} | Page ${pageNumber} of ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  )
}
